spring:
  application:
    name: turbine
server:
  port: 3000


eureka:
#  instance:
#    metadata-map:
#       management.port: ${management.port:8081}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
turbine:
  app-config: ORDER-EUREKA-HYSTRIC
  cluster-name-expression: "'default'"
  combine-host-port: true
#  aggregator:
#      clusterConfig: CUSTOMERS
# spring官方文档 http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.2.RELEASE/multi/multi__hystrix_timeouts_and_ribbon_clients.html