spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/zhaomeng?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false"
    driver-class-name: com.mysql.jdbc.Driver
    username: "root"
    password: "root"
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
server:
  port: 8083
eureka:
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
#    metadata-map:
#      zone: abc
#      zhaomeng: bcd
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}




