spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/supermenGMM/spring-cloud-config.git
          username: supermenGMM
          password: 561359mm
          skip-ssl-validation: true

#          timeout: 5
#          username: 852458550@qq.com
server:
    port: 8012
