spring:
  datasource:
    url: "jdbc:mysql://10.3.200.4:3306/zhaomeng?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false"
    driver-class-name: com.mysql.jdbc.Driver
    username: "root"
    password: "root"
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
  application:
      name: eureka-upload


eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
server:
  port: 8085
