server:
  port: 2222
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:1111/eureka/
    enabled: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
