spring:
  application:
    name: api-geteway
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /v1
#前缀,可以加版本号
  routes:
    EUREKA-PRODUCT-HOME2: /product/**

    haha:
      path: /order/**
      serviceId: order-customer

