server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka
    enabled: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
